FROM apache/airflow:2.10.4-python3.11

USER root
COPY requirements.txt /tmp/requirements.txt
COPY src /opt/airflow/src
COPY scripts /opt/airflow/scripts
RUN chown -R airflow:0 /opt/airflow/src /opt/airflow/scripts

USER airflow
RUN pip install --no-cache-dir -r /tmp/requirements.txt

ENV PYTHONPATH=/opt/airflow
