apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    namespace: alpha-trading
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:7MuKHYX1doAa8a7YgsppmzZKOG2I4OFBa9Zc61CpF2bqNdAOf5ix3t3ojJd5VDcPlQpBvDEf2oZbkvm774FbgA==,iv:nBa4WHgneBB8LSVtYI5+ECzOgsyfjZfNDB843T9PKXc=,tag:7h86RUgKHcofOeoIq/a7+A==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:5mPH0KelqSXaYuijr0Ck4zzfJNY90EOJPDmqoNG2TdVwCE4GzD2MmFxUY2REXmYNzgvyO+jT8RUrvQER7b7MkijuGCwM/f97PMuQo8jZXtowyMwJrExg3+nHvWovEmFfkVZPQjmrDzpNyg==,iv:wm0k9MshZYnmOf6zKk9Fx72chai6+4hcm9n1YrhBUW0=,tag:VXTP+qG3zSCy650bfvt2NA==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:44DyawZzP2/J1Q==,iv:Cw60tsHqBQBwGPAcimjoxSbXO4H/+ohA6D2I78VeoPY=,tag:6Z8j3yRLNGOIYzGtLUKqEw==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:Owxb+JnPw7vGTw==,iv:lFqNsO/BXzGynD/0kfBn16dohiH+CKwRxiPiLMhhyPc=,tag:pYOte8KHjPwi7I6mdZoS+w==,type:str]
    KIS_IS_PAPER_TRADING: ENC[AES256_GCM,data:tP399Q==,iv:6bWPaCexrWw4J8A8wfoluXnh7NSDMxU/PQxKY7EpApU=,tag:GYWnMmGhtllcmr9gh7+lyA==,type:str]
    KIS_PAPER_APP_KEY: ENC[AES256_GCM,data:6snOvwL4nic7LGCraUN8CZw9Pqid/llQ+U9kmp4/WXPAJ9X5,iv:nIqPogAkQ7vTo5rL+jnK7xVGCEws4z4wNlNZybTMlPs=,tag:tU8KsvwLq5bXz28W3xlpqg==,type:str]
    KIS_PAPER_APP_SECRET: ENC[AES256_GCM,data:QQD151SoG8a5xNJwj4WzwqHpJTIeC0C9dBOjAHGeZ/q9GekdfLqgfTeNN6luv32kTVjCQsCo2S6wZ6blQIy4Foa6jN6m01FxT2no2YnoAVb86nexCiz2QNVIZ6mdWWNsDbuE6W8nE/JTZEoK/9h7BMI3aGWyKsC7SkOrE0EfmSc8sb/ufECslvCyhvVoP634JqkshzHsC5pJzOFdoiSpuV91PNRYSRnumaxTU+I3hNcUaHcY,iv:anaPi8glzeLZ9cAGh3FRhjA+H3t0BDKil79wm7RpE/E=,tag:yy7nCDP84HpcSEVBOvEM0Q==,type:str]
    KIS_PAPER_ACCOUNT_NUMBER: ENC[AES256_GCM,data:sc3+BRldr/hhbTw=,iv:VCt0LafptnbUh90zQ3+yE2MV/Mke8QZjXPPKLqjnfQ4=,tag:3yB7E6kszstNIyIoZuAB6A==,type:str]
    KIS_REAL_APP_KEY: ENC[AES256_GCM,data:9CnRblqRR0b3YF9hf5fq5wYxaHW2ye5xnMlWiLvXn4p0IZHc,iv:LJ6MdkqBKVcJ9w2LTkMpPbsyk/AOTSRs5kGPNGkRakY=,tag:kGu14KIYCYnSMiZ96zH55g==,type:str]
    KIS_REAL_APP_SECRET: ENC[AES256_GCM,data:+my51dT5ZqQJanvNWRVG29sEtTvqQ8N1/CCWsITw8TgybUQPzpghkZUxNfFs1KRkxvrqd00SICqk3GgSO7auO/VZmOx++Qzspznn2YahG8HR6KHVYv7m72T8JMEjoZa2c92jvBL9HWs7IG9zdMSdp/hlV3zWVp35H658qNlzwJUFhN324a4krfeBhz75o/zOKajWnUCxf7+Vx/sSvszC4T9ttWg3zK3nkX0micFOhq25G2jK,iv:LAipmKHWAwKAqUPak3HT2l+WY6YoX7K/bYcaIGvNQ44=,tag:5TwgXevzQdDTjO2YS76cLw==,type:str]
    KIS_REAL_ACCOUNT_NUMBER: ENC[AES256_GCM,data:MQMKRRobcIkOJQs=,iv:HQvEaeK94kjCs+bPB0gUIgZ53NewQ2XoYIgSNXaM+0E=,tag:svmdBsQ6iq+AL2pQujgmBg==,type:str]
    REAL_TRADING_CONFIRMATION_CODE: ENC[AES256_GCM,data:5xjvulZ35grZst4mhSsOutFXQ7njUSDUQw==,iv:Nn3jIshq+mohkCxkbIvDTfiSWHoY5JUnAhKhzPeb8Q8=,tag:c/WTfJWjFZ+ktm25ODpwTw==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:oLX85lxmxy59rzVYdQiK/YQxcH3WmaXxiJYjqXSI7Dk/+k/VoIqocyRFKTLjUg==,iv:JRF4g0/CYAXgEO8L2O0z+g9wE0033rfh69wHoGVCNjs=,tag:n1qKQ7JP6d8LRXl3X8oy7w==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:cFCJvRrga9OU0A==,iv:MrULZWaOjR3e73KZGPGDM1GFODnCDQtK5yXd5xJu8Zs=,tag:FCgP2g4Kzl4JavA6vhUu6w==,type:str]
sops:
    age:
        - recipient: age18qupwj35fuedm7phyusgx4ksgkfsnk6q999dstxecc8hrmrpkdesf8yfap
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZDNkb0xTZlFNTU1PRVhu
            RkRWRXRuYUtYN3hHYzRCWU1zcnU2YTRLYVNzCmZ5c2krZmljZTA1SmJKa29tcytJ
            ejIxVTIzWGZyZi8yTEV1Mkx5L0w0djQKLS0tIEZsaTRlR1N2N0c4VDd0b1RSbTln
            UXhsaUV3aEtOODVDbk04eFJkUVVhNDgKmCV4aFPP4UVL2hAy8piXsCwPnZFIx3SN
            w6hm+53ewMJZ6qaySoZF270cC0QV/K1hAMkELZhW9inAAveB+IOofQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T08:35:50Z"
    mac: ENC[AES256_GCM,data:t9ZvdG/9uKOGrDOLF2QRX5RzfdBiawR43/3hWHCEjse0q47gK/LWn7/uUk2FYGV8pavtOTTNpgeo9Y33q3TtmYn2JE+K65PNshcbGm7yjgOXADLOINzKWQnyuUNZdkinAtchcurDOmB8DL8OUABK4zLLdg0sQGis3lasGD+SRcI=,iv:mZqo9W8zARI+vwpLNF2fGWzsjQnUYqGNzK5dS7He/iM=,tag:zs0ceS6yNKCcgdY7+OBuVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
